services:
  ulventech_db:
    container_name: ulventech_db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ulventech_db-data:/var/lib/postgresql/data

  ulventech_backend:
    container_name: ulventech_backend
    image: ulventech_backend:1.0.0
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 8000:8000
    depends_on:
      - ulventech_db
  
  ulventech_frontend:
    container_name: ulventech_frontend
    image: ulventech_frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - ulventech_backend

volumes:
  ulventech_db-data:
    driver: local
  